name: Matrix

on: [ push ]

# jobs:
#   node-version:
#     runs-on: ubuntu-16.04
#     steps:
#       - name: Log Node Version
#         run: node -v
#       - uses: actions/setup-node@v1
#         with:
#           node-version: 6
#       - name: Log Node Version
#         run: node -v

jobs:
  node-version:
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node_version: [6, 8, 10]
    # runs-on: ubuntu-16.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log Node Version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Log Node Version
        run: node -v
